### PR TITLE
HAL_F4Light: Fix inverter on Omnibus F4 V3

### PR DESCRIPTION
**Pull request by sh83**
Omnibus F4 V3 has bidirectional inverter on uart6, controlled by PC8, PC9. Other versions have this pins connected to small pad on PCB and are usually unused.

### CODE REVIEW

**Comment by night-ghost** [comment]
I think we should add a new target OmnibusV3 and do it there, because I use AirbotV2 with compass via Soft_I2C

**Comment by sh83** [comment]
You have soldered compass to small pads on pcb? I2C2 on sh1.0 6 pin connector should be ok.

**Comment by Kelly-Foster** [comment]
+1 on direct support for Omnibus V3. The more I learn about this FC, the more changes I see relative to Pro and V2.

**Comment by Landflieger** [comment]
+1 on direct support for Omnibus V3 also from me

**Comment by sh83** [comment]
@Landflieger Omnibus F4 Pro V3 should use AirbotV2 target. This PR is for Omnibus F4 V3 and V5, they are different from your board.

**Comment by Landflieger** [comment]
@sh83 sorry, I mixed up the boards

**Comment by night-ghost** [comment]
created new target with this fixes, so closed

**Comment by sh83** [comment]
Ok, thank you!

**Pull request closed without merging**
