### PR TITLE
Update 1_read_me.md

### PR DESCRIPTION
**Pull request by estebanavv**
Just change reference from HAL to BRD_

### CODE REVIEW

**Comment by night-ghost** [comment]
thanks but now PRs should be directly to Ardupilot, not to me

**Comment by estebanavv** [comment]
I can do both. We use links from this fork to download binaries and to share info. If I do master it would take sometime to get here.

**Comment by night-ghost** [comment]
just prefix PRs to master with HAL_F4Light: , and time to merge will be reduced to one day

**Comment by night-ghost** [comment]
now you did PR to wrong branch, actual branch is now Revo, RevoMini is damaged after HAL merged upstream

**Comment by estebanavv** [comment]
i am sorry next time I'll do only master.

**Comment by night-ghost** [comment]
I did similar fixes in all readme, though

**Comment by night-ghost** [comment]
so please close PR on master

**Pull request merged**
